import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './context/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${inter.className} w-full h-screen bg-white selection:bg-indigo-600 dark:selection:bg-teal-700 selection:text-white dark:bg-dodgerblue-950 `}
			>
				<div className="dark:text-white">
					<Providers>{children}</Providers>
				</div>
			</body>
		</html>
	);
}
